language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 09f8d4a4bada0409735e1182a607c55af45052c4
  local_dir: build
  on:
    branch: yt_parser