language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 673e7144cca2123d0ca5264681db2408eebb4983
  local_dir: build
  on:
    branch: yt_parser